#!/usr/bin/env python3
"""async comprehe... task 1"""
import asyncio
from typing import List

task_0_function = __import__('0-async_generator').async_generator

"""
This module defines a coroutine that collects 10 random numbers
from an asynchronous generator using an asynchronous comprehension.
"""


async def async_comprehension() -> List[float]:
    """
    Collects 10 random numbers from async_generator using async comprehension.

    This coroutine uses an asynchronous comprehension to collect 10 random
    float numbers generated by the async_generator coroutine.

    Returns:
        A list of 10 random float numbers collected from async_generator.
    """
    return [i async for i in task_0_function()]
